ci: update toolbox.yaml file according to latest rook version
ceph/persistent-volume-migrator pull request #26
Opened 2021-11-22 09:11 UTC by subhamkrai

updating latest toolbox.yaml file according to latest rook version

Signed-off-by: subhamkrai <srai@redhat.com>

2021-11-22 09:11 UTC, subhamkrai commented
wait till #22

2021-11-22 20:17 UTC, travisn requested changes

2021-11-23 06:44 UTC, subhamkrai commented on tests/manifests/toolbox.yaml
> +          image: rook/ceph:master
done.

2021-11-23 06:46 UTC, Madhu-1 approved these changes

2021-11-23 14:46 UTC, merged